intmult: integer_multiplication.cpp
	g++ -std=c++14 integer_multiplication.cpp -o intmult

clean:
	rm -rf intmult a.out

tes: test/first.cpp include/catch.hpp
	g++ -std=c++14 include/catch.hpp test/first.cpp  -o first